version: '3'
services:
  publish:
    build: ./publish
    image: asatrya/iot-publish:1.0
    env_file:
      - .env
    volumes:
      - ./publish:/app
      - ./key.json:/usr/local/etc/key.json

  process:
    build: ./process
    image: asatrya/iot-process:1.0
    env_file:
      - .env
    volumes:
      - ./process:/app
      - ./key.json:/usr/local/etc/key.json

  visualization:
    build: ./visualization
    image: asatrya/iot-visualization:1.0
    env_file:
      - .env
    volumes:
      - ./visualization:/app
      - ./key.json:/usr/local/etc/key.json
    ports:
      - 9000:9000

  explore:
    build: ./explore
    image: asatrya/iot-explore:1.0
    env_file:
      - .env
    volumes:
      - ./explore:/app
      - ./key.json:/usr/local/etc/key.json
    ports:
      - 80:80
      - 443:443